-- Appointments and the pre-visit patient report.
--
-- A report is a database row (patient_reports.data, jsonb) that the frontend or a document
-- generator renders later. It is generated by the `generate-report` edge function about 12 hours
-- before the appointment: pg_cron polls every 10 minutes and calls the function through pg_net.
-- An appointment booked less than 12 hours ahead is picked up at the next poll.

create extension if not exists pg_cron;
create extension if not exists pg_net;

-- Appointments ------------------------------------------------------------------

create table public.appointments (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.profiles (id) on delete cascade,
  -- Set when the doctor is a linked clinician; doctor_name covers doctors outside Digna.
  clinician_id uuid references public.profiles (id) on delete set null,
  doctor_name text check (char_length(doctor_name) <= 100),
  scheduled_at timestamptz not null,
  status text not null default 'scheduled' check (status in ('scheduled', 'cancelled', 'completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.appointments enable row level security;
create index appointments_patient_scheduled_idx on public.appointments (patient_id, scheduled_at);
create index appointments_clinician_idx on public.appointments (clinician_id);
-- The report poller only looks at upcoming, scheduled visits.
create index appointments_due_idx on public.appointments (scheduled_at) where status = 'scheduled';

create trigger appointments_set_updated_at before update on public.appointments
  for each row execute function private.set_updated_at();

create policy appointments_select on public.appointments for select to authenticated
  using (patient_id = (select auth.uid()) or private.is_care_team(patient_id));
create policy appointments_insert_own on public.appointments for insert to authenticated
  with check (patient_id = (select auth.uid()));
create policy appointments_update_own on public.appointments for update to authenticated
  using (patient_id = (select auth.uid())) with check (patient_id = (select auth.uid()));
create policy appointments_delete_own on public.appointments for delete to authenticated
  using (patient_id = (select auth.uid()));

-- Reports ------------------------------------------------------------------------

-- Written only by the generate-report function (service role). Patients and their care
-- team can read them.
create table public.patient_reports (
  id uuid primary key default gen_random_uuid(),
  appointment_id uuid not null unique references public.appointments (id) on delete cascade,
  patient_id uuid not null references public.profiles (id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'ready', 'failed')),
  attempts int not null default 0,
  period_start date,
  period_end date,
  generated_at timestamptz,
  model text,
  -- 'llm' when the model wrote the summary, 'fallback' when the template did.
  narrative_source text check (narrative_source in ('llm', 'fallback')),
  data jsonb,
  -- A short machine code, never message text.
  error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.patient_reports enable row level security;
create index patient_reports_patient_idx on public.patient_reports (patient_id);

create trigger patient_reports_set_updated_at before update on public.patient_reports
  for each row execute function private.set_updated_at();

create policy patient_reports_select on public.patient_reports for select to authenticated
  using (patient_id = (select auth.uid()) or private.is_care_team(patient_id));

-- A moved appointment needs a fresh report for the new time.
create or replace function private.reset_report_on_reschedule()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.scheduled_at is distinct from old.scheduled_at then
    delete from public.patient_reports where appointment_id = new.id;
  end if;
  return new;
end;
$$;
revoke all on function private.reset_report_on_reschedule() from public;

create trigger appointments_reset_report after update of scheduled_at on public.appointments
  for each row execute function private.reset_report_on_reschedule();

-- Job plumbing -------------------------------------------------------------------

-- One row: where the function lives and the shared secret that proves a call came from the
-- database. Set `url` per environment, e.g.
--   update private.report_job_config set url = 'https://<ref>.supabase.co/functions/v1/generate-report';
-- With no url the poller does nothing.
create table private.report_job_config (
  id boolean primary key default true check (id),
  url text,
  secret text not null default encode(extensions.gen_random_bytes(32), 'hex')
);
insert into private.report_job_config (id) values (true) on conflict do nothing;

-- The edge function checks the secret through this, so it never needs to read it.
create or replace function public.verify_report_job_secret(p_secret text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (select 1 from private.report_job_config where secret = p_secret);
$$;
revoke all on function public.verify_report_job_secret(text) from public, anon, authenticated;
grant execute on function public.verify_report_job_secret(text) to service_role;

-- Finds appointments inside the 12-hour window that still need a report and asks the edge
-- function to build each one. A row in patient_reports is the claim: 'pending' is retried after
-- 30 minutes and 'failed' is retried, both up to 3 attempts.
create or replace function private.dispatch_due_reports()
returns int
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_url text;
  v_secret text;
  r record;
  v_count int := 0;
begin
  select c.url, c.secret into v_url, v_secret from private.report_job_config c where c.id;
  if v_url is null then
    return 0;
  end if;

  for r in
    select a.id, a.patient_id
    from public.appointments a
    left join public.patient_reports p on p.appointment_id = a.id
    where a.status = 'scheduled'
      and a.scheduled_at > now()
      and a.scheduled_at <= now() + interval '12 hours'
      and (
        p.id is null
        or (p.status = 'failed' and p.attempts < 3)
        or (p.status = 'pending' and p.updated_at < now() - interval '30 minutes' and p.attempts < 3)
      )
    order by a.scheduled_at
    limit 20
    for update of a skip locked
  loop
    insert into public.patient_reports (appointment_id, patient_id, status, attempts)
    values (r.id, r.patient_id, 'pending', 1)
    on conflict (appointment_id) do update
      set status = 'pending', attempts = public.patient_reports.attempts + 1, updated_at = now();

    perform net.http_post(
      url := v_url,
      headers := jsonb_build_object('Content-Type', 'application/json', 'x-job-secret', v_secret),
      body := jsonb_build_object('appointment_id', r.id),
      timeout_milliseconds := 120000
    );
    v_count := v_count + 1;
  end loop;

  return v_count;
end;
$$;
revoke all on function private.dispatch_due_reports() from public;

select cron.schedule('dispatch-due-reports', '*/10 * * * *', 'select private.dispatch_due_reports()');
